language: scala

sudo: required

scala:
  - "2.12.1"

jdk:
  - oraclejdk8

notifications:
  email:
    recipients:
    - kpritam@thoughtworks.com
    - uvjoshi@thoughtworks.com
    on_success: never
    on_failure: always


#services:
#  - docker

#before_install:
#  - docker-compose up -d

script:
  - sbt -J-XX:ReservedCodeCacheSize=128m ++$TRAVIS_SCALA_VERSION ";scalastyle;test;coverageReport"

before_cache:
  - find $HOME/.ivy2 -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt  -name "*.lock"               -print -delete

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot

env:
  global:
    # encrypt with: travis encrypt BINTRAY_USER=...
    - secure: ""
    # encrypt with: travis encrypt BINTRAY_PASS=...
    - secure: ""
